# Generated by Django 5.0.4 on 2024-05-26 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
    ]
