# Generated by Django 5.0.4 on 2024-05-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
