# Generated by Django 5.0.4 on 2024-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_topics_userprofile_nama_lengkap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nama_lengkap',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
